"""Authoritative Neomax test-suite registry."""

from typing import NamedTuple


class SuiteSpec(NamedTuple):
    name: str
    responsibility: str
    tests: tuple


SUITE_REGISTRY = (
    SuiteSpec(
        "test_product_contracts",
        "Public packaging, provider parity, launch selection, goals, and delegation safety.",
        (
            "test_public_product_contract",
            "test_provider_workflow_parity_and_install",
            "test_neomax_engine_selection",
            "test_goal_construction",
            "test_validation",
            "test_delegation_brief_check",
            "test_delegation_gate",
        ),
    ),
    SuiteSpec(
        "test_opencode",
        "OpenCode model policy, launchers, event parsing, and local telemetry.",
        (
            "test_opencode_ox_alpha_policy_and_events",
            "test_opencode_launchers_dry_run",
            "test_opencode_local_telemetry",
        ),
    ),
    SuiteSpec(
        "test_kimi_grok",
        "Kimi Code and Grok models, authentication, launchers, events, and telemetry.",
        (
            "test_kimi_models_events_and_telemetry",
            "test_grok_models_events_telemetry_and_launchers",
        ),
    ),
    SuiteSpec(
        "test_codex",
        "Codex models, fast mode, live usage, children, and weekly-window policy.",
        (
            "test_codex_fast_mode",
            "test_codex_children_kinds",
            "test_codex_usage_live",
            "test_codex_weekly_only_rotation",
            "test_codex_model_family",
        ),
    ),
    SuiteSpec(
        "test_account_selection",
        "Account eligibility, load spreading, pauses, solo mode, and orchestrator selection.",
        (
            "test_reset_normalization_and_cooldown",
            "test_pick_account_spread_bias",
            "test_default_fanout_cap",
            "test_fleet_concurrency_cap",
            "test_even_usage_distribution",
            "test_pause_unpause",
            "test_solo_mode",
            "test_pick_orch_account",
            "test_pick_orch_anti_stack",
            "test_orchestrators_on_account",
            "test_colocation_banner",
            "test_dedicated_orchestrator",
            "test_weekly_limit_and_selection",
            "test_fleet_scope",
            "test_weekly_deadline_selection",
        ),
    ),
    SuiteSpec(
        "test_rotation_handoff",
        "In-place rotation, provider-neutral handoff, armed markers, and anti-herd behavior.",
        (
            "test_session_rotate",
            "test_orchestrator_handoff",
            "test_handoff_orch_account_formatting",
            "test_universal_provider_rotate",
            "test_armed_rotate_marker",
            "test_rotation_antiherd_and_autorotate",
        ),
    ),
    SuiteSpec(
        "test_usage",
        "Quota fetching, usage ledgers, pricing, backoff, watchers, and keepalive.",
        (
            "test_fetch_claude_usage",
            "test_keepalive",
            "test_usage_tracking",
            "test_billing_id_dedup",
            "test_usage_dates_and_pricing",
            "test_usage_429_backoff",
            "test_usage_watch_self_heal_backfill",
            "test_usage_since_window",
            "test_usage_watch_malformed_token_values",
        ),
    ),
    SuiteSpec(
        "test_status_telemetry",
        "Status aggregation, ambient sessions, history, subagents, and portal transport.",
        (
            "test_history_persistence",
            "test_live_children_parse",
            "test_gather_status_subagent_count",
            "test_effective_status_malformed",
            "test_ambient_agent_detection",
            "test_ambient_active_mains",
            "test_solo_ambient_visibility",
            "test_workflow_journal_recency",
            "test_fleet_visibility_at_scale",
            "test_subagent_tokens",
            "test_portal_send_disconnect",
        ),
    ),
    SuiteSpec(
        "test_worker_lifecycle",
        "Worker validation, cleanup, process liveness, failover, and detached dispatch.",
        (
            "test_git_missing_cwd",
            "test_clean_force_repo_deleted",
            "test_kill_pause_lossless",
            "test_worker_alive_group_and_orphan_sweep",
            "test_worktree_outcome_killed_guard",
            "test_cross_engine_failover",
            "test_dispatch_detach_default",
        ),
    ),
    SuiteSpec(
        "test_worktrees_diffs",
        "Worktree recovery, cleanup safety, planning scouts, subagent history, and exact diffs.",
        (
            "test_worktree_changes_fail_safe",
            "test_clean_refuses_unmerged_work",
            "test_plan_mode_scouts",
            "test_subagent_history_stats",
            "test_exact_diffs_and_projects",
            "test_extract_patches_bounded_and_robust",
            "test_ensure_workdir_recovery",
        ),
    ),
    SuiteSpec(
        "test_orchestrator_runtime",
        "Concurrent orchestrators, turn hooks, orientation, modes, and hardening.",
        (
            "test_orchestrator_coordination",
            "test_turn_hook_preserves_model_choice",
            "test_orchestrator_turn_reminder",
            "test_hardening_regressions",
            "test_orient_directive",
            "test_modes_quick_actions",
        ),
    ),
    SuiteSpec(
        "test_scheduler_reconcile",
        "Conflict resolution, area locks, scheduler validation, healing, queues, and tidy.",
        (
            "test_union_resolve",
            "test_area_lock_stale_reclaim",
            "test_run_all_norm_keys_and_validation",
            "test_run_all_stall_and_no_record",
            "test_reconcile_heal_dedup_and_age",
            "test_agent_queue",
            "test_tidy_merged_runs",
        ),
    ),
    SuiteSpec(
        "test_issues_ci",
        "Continuous-integration classification and cross-repository issue lifecycle.",
        (
            "test_ci_billing_tolerance",
            "test_shepherd_empty_rollup",
            "test_issue_pipeline",
            "test_issue_batch_claim",
        ),
    ),
    SuiteSpec(
        "test_projects_tasks",
        "Portable project registration, coordinated worktrees, and durable task backlog.",
        (
            "test_project_registration",
            "test_portable_project_worktrees",
            "test_task_backlog",
        ),
    ),
    SuiteSpec(
        "test_auth_credentials",
        "Account identity, OAuth refresh, TLS, and explicit credential rotation.",
        (
            "test_account_identity_robustness",
            "test_oauth_refresh",
            "test_ssl_context_has_trust_store",
            "test_rotate_auth",
        ),
    ),
    SuiteSpec(
        "test_models",
        "Default-model policy and explicit local-model overrides.",
        ("test_default_model_switch",),
    ),
)

TEST_ORDER = (
    "test_public_product_contract",
    "test_provider_workflow_parity_and_install",
    "test_neomax_engine_selection",
    "test_goal_construction",
    "test_opencode_ox_alpha_policy_and_events",
    "test_opencode_launchers_dry_run",
    "test_kimi_models_events_and_telemetry",
    "test_grok_models_events_telemetry_and_launchers",
    "test_opencode_local_telemetry",
    "test_codex_fast_mode",
    "test_git_missing_cwd",
    "test_validation",
    "test_clean_force_repo_deleted",
    "test_reset_normalization_and_cooldown",
    "test_worktree_changes_fail_safe",
    "test_clean_refuses_unmerged_work",
    "test_handoff_orch_account_formatting",
    "test_universal_provider_rotate",
    "test_usage_watch_malformed_token_values",
    "test_union_resolve",
    "test_area_lock_stale_reclaim",
    "test_run_all_norm_keys_and_validation",
    "test_ensure_workdir_recovery",
    "test_run_all_stall_and_no_record",
    "test_reconcile_heal_dedup_and_age",
    "test_fetch_claude_usage",
    "test_account_identity_robustness",
    "test_keepalive",
    "test_usage_tracking",
    "test_billing_id_dedup",
    "test_usage_dates_and_pricing",
    "test_usage_429_backoff",
    "test_ambient_agent_detection",
    "test_usage_watch_self_heal_backfill",
    "test_codex_children_kinds",
    "test_ambient_active_mains",
    "test_usage_since_window",
    "test_dedicated_orchestrator",
    "test_subagent_history_stats",
    "test_exact_diffs_and_projects",
    "test_turn_hook_preserves_model_choice",
    "test_orchestrator_turn_reminder",
    "test_hardening_regressions",
    "test_extract_patches_bounded_and_robust",
    "test_delegation_brief_check",
    "test_cross_engine_failover",
    "test_rotate_auth",
    "test_plan_mode_scouts",
    "test_kill_pause_lossless",
    "test_worker_alive_group_and_orphan_sweep",
    "test_worktree_outcome_killed_guard",
    "test_orient_directive",
    "test_codex_usage_live",
    "test_pick_account_spread_bias",
    "test_default_fanout_cap",
    "test_fleet_concurrency_cap",
    "test_even_usage_distribution",
    "test_pause_unpause",
    "test_solo_mode",
    "test_session_rotate",
    "test_pick_orch_account",
    "test_pick_orch_anti_stack",
    "test_orchestrators_on_account",
    "test_colocation_banner",
    "test_orchestrator_coordination",
    "test_modes_quick_actions",
    "test_oauth_refresh",
    "test_project_registration",
    "test_portable_project_worktrees",
    "test_subagent_tokens",
    "test_workflow_journal_recency",
    "test_fleet_visibility_at_scale",
    "test_ci_billing_tolerance",
    "test_shepherd_empty_rollup",
    "test_issue_pipeline",
    "test_issue_batch_claim",
    "test_agent_queue",
    "test_solo_ambient_visibility",
    "test_delegation_gate",
    "test_armed_rotate_marker",
    "test_task_backlog",
    "test_tidy_merged_runs",
    "test_default_model_switch",
    "test_codex_model_family",
    "test_codex_weekly_only_rotation",
    "test_history_persistence",
    "test_live_children_parse",
    "test_gather_status_subagent_count",
    "test_effective_status_malformed",
    "test_ssl_context_has_trust_store",
    "test_weekly_limit_and_selection",
    "test_fleet_scope",
    "test_orchestrator_handoff",
    "test_portal_send_disconnect",
    "test_weekly_deadline_selection",
    "test_dispatch_detach_default",
    "test_rotation_antiherd_and_autorotate",
)
