"""Authoritative Neomax domain-module registry."""

from typing import NamedTuple


class ModuleSpec(NamedTuple):
    name: str
    responsibility: str
    exports: tuple


MODULE_REGISTRY = (
    ModuleSpec(
        "config",
        "Runtime paths, pricing, and provider-scope configuration.",
        (
            "base64",
            "datetime",
            "email",
            "fcntl",
            "globmod",
            "hashlib",
            "json",
            "os",
            "re",
            "shutil",
            "signal",
            "sqlite3",
            "ssl",
            "subprocess",
            "sys",
            "tempfile",
            "time",
            "urllib",
            "uuidlib",
            "HOME",
            "NEOMAX_REPO_DIR",
            "STATE_DIR",
            "RUNS_DIR",
            "LOGS_DIR",
            "USAGE_DIR",
            "EVENTS_DIR",
            "WORKTREES_DIR",
            "COOLDOWN_FILE",
            "PAUSED_FILE",
            "HISTORY_DB",
            "HISTORY_LOGS",
            "USAGE_LEDGER_DIR",
            "USAGE_WATCH_STATE",
            "CLAUDE_BIN",
            "CODEX_BIN",
            "OPENCODE_BIN",
            "KIMI_BIN",
            "GROK_BIN",
            "CACHE_READ_MULT",
            "CLAUDE_CACHE_WRITE_MULT",
            "OPENAI_CACHE_WRITE_MULT",
            "MODEL_IO",
            "_derive_pricing",
            "PRICING",
            "PRICING_DEFAULT",
            "model_pricing",
            "usage_cost",
            "DEFAULT_COOLDOWN_S",
            "allowed_engines",
            "engine_in_scope",
            "CLAUDE_OPUS5_MODEL",
            "CLAUDE_OPUS_MODEL",
            "CLAUDE_OPUS_MODEL_1M",
            "CLAUDE_FABLE_MODEL",
            "CLAUDE_OPUS48_MODEL",
            "CLAUDE_DEFAULT_MODEL",
            "CLAUDE_DEFAULT_MODEL_1M",
            "CODEX_MODELS",
            "CODEX_MODEL",
            "CODEX_MODEL_DEFAULT_TIER",
        ),
    ),
    ModuleSpec(
        "models",
        "Provider model resolution, profiles, and OpenCode policy.",
        (
            "_explicit_model",
            "resolve_claude_model",
            "resolve_codex_model",
            "codex_model_tier",
            "CODEX_SERVICE_TIER",
            "CODEX_EFFORTS",
            "OPENCODE_MODEL",
            "OPENCODE_POLICY_FILE",
            "KIMI_MODELS",
            "KIMI_MODEL",
            "GROK_MODEL",
            "resolve_opencode_model",
            "resolve_kimi_model",
            "resolve_grok_model",
            "default_model",
            "opencode_policy_content",
            "ENGINES",
            "orch_profile",
            "orch_reserved",
            "engine_profiles",
            "worker_profiles",
            "WORKER_DIRECTIVE",
            "codex_goal_block",
            "CONTINUATION_NOTE",
            "LIMIT_RE",
            "INTERRUPT_RE",
            "profiles",
            "err",
        ),
    ),
    ModuleSpec(
        "account_auth",
        "Profile discovery and provider authentication state.",
        (
            "keychain_service",
            "opencode_auth_path",
            "kimi_auth_method",
            "logged_in",
            "OPENCODE_RATE_RE",
        ),
    ),
    ModuleSpec(
        "telemetry_opencode",
        "OpenCode session and usage telemetry.",
        (
            "opencode_data_dir",
            "opencode_db_path",
            "_opencode_epoch",
            "_opencode_int",
            "_opencode_model",
            "_opencode_error",
            "_opencode_lines",
            "opencode_profile_snapshot",
            "opencode_usage_snapshots",
            "opencode_telemetry_profiles",
        ),
    ),
    ModuleSpec(
        "telemetry_kimi",
        "Kimi session and usage telemetry.",
        (
            "kimi_telemetry_profiles",
            "_kimi_wire_summary",
            "kimi_profile_snapshot",
            "kimi_usage_snapshots",
        ),
    ),
    ModuleSpec(
        "telemetry_grok",
        "Grok session and usage telemetry.",
        (
            "grok_telemetry_profiles",
            "_grok_prompt_usage",
            "_grok_updates",
            "grok_profile_snapshot",
            "grok_usage_snapshots",
        ),
    ),
    ModuleSpec(
        "account_state",
        "Cooldowns, pauses, reset normalization, and live counts.",
        (
            "load_cooldowns",
            "set_cooldown",
            "cooling_down",
            "clear_cooldown",
            "load_paused",
            "is_paused",
            "set_paused",
            "MAX_RESET_HORIZON_S",
            "to_epoch_seconds",
            "normalize_reset_epoch",
            "live_counts",
            "registry_live_counts",
            "AGENT_ACTIVE_WINDOW_S",
            "WORKFLOW_RECENT_S",
        ),
    ),
    ModuleSpec(
        "agent_activity",
        "Native agent activity discovery.",
        ("ambient_agent_details", "ambient_live_agents", "CLAUDE_META_TYPES"),
    ),
    ModuleSpec(
        "session_headers",
        "Claude and Codex session metadata parsing.",
        (
            "_claude_tail_active",
            "_codex_tail_active",
            "_codex_session_live",
            "_claude_head_meta",
            "_codex_head_meta",
        ),
    ),
    ModuleSpec(
        "provider_activity",
        "OpenCode, Kimi, and Grok interactive activity.",
        (
            "opencode_main_details",
            "opencode_agent_details",
            "kimi_main_details",
            "kimi_agent_details",
            "grok_main_details",
            "grok_agent_details",
        ),
    ),
    ModuleSpec(
        "ambient_sessions",
        "Fleet-wide interactive process and session activity.",
        ("ambient_main_details", "ambient_active_mains", "process_live_counts"),
    ),
    ModuleSpec(
        "http_client",
        "TLS, HTTP, and Claude OAuth access.",
        (
            "CLAUDE_USAGE_URL",
            "CLAUDE_PROFILE_URL",
            "EMAIL_FRESH_S",
            "USAGE_FRESH_S",
            "USAGE_STALE_LABEL_S",
            "USAGE_RL_BACKOFF_S",
            "USAGE_STALE_OK_S",
            "USAGE_HTTP_TIMEOUT_S",
            "_SSL_CTX",
            "ssl_context",
            "_certifi_where",
            "http_get_json",
            "http_post_json",
            "CLAUDE_OAUTH_TOKEN_URL",
            "CLAUDE_OAUTH_CLIENT_ID",
            "CLAUDE_OAUTH_USER_AGENT",
            "REFRESH_ATTEMPT_COOLDOWN_S",
            "iso_to_epoch",
            "claude_oauth_token",
            "_stored_oauth_blob",
            "claude_refresh_token",
            "_claude_local_identity",
        ),
    ),
    ModuleSpec(
        "projects",
        "Portable project discovery and registration.",
        (
            "DEFAULT_PROJECTS_FILE",
            "PROJECTS_FILE",
            "LOCAL_PROJECTS_FILE",
            "_DEFAULT_PROJECTS",
            "_project_map",
            "load_projects",
            "project_of",
            "save_projects",
            "project_slug",
            "discover_project_repos",
            "ensure_launch_project",
            "is_unregistered_project_dir",
            "register_project",
            "cmd_project_register",
        ),
    ),
    ModuleSpec(
        "tasks",
        "Durable project backlog and task commands.",
        (
            "TASKS_FILE",
            "TASK_STATUSES",
            "TASK_OPEN_STATUSES",
            "TASK_DONE_STATUSES",
            "load_tasks",
            "_save_tasks_locked",
            "task_add",
            "task_update",
            "task_remove",
            "tasks_for_project",
            "_TASK_STATUS_VERB",
            "cmd_task",
        ),
    ),
    ModuleSpec(
        "credentials",
        "Credential storage, identity metadata, and rotation records.",
        (
            "AUTH_BACKUPS",
            "AUTH_ROTATIONS",
            "read_claude_cred_blob",
            "write_claude_cred_blob",
            "_claude_json_path",
            "_read_oauth_account",
            "_write_oauth_account",
            "_log_auth_rotation",
            "recent_auth_rotations",
            "_resolve_profile",
        ),
    ),
    ModuleSpec(
        "interactive_sessions",
        "Interactive session history and reporting.",
        ("gather_sessions", "cmd_sessions"),
    ),
    ModuleSpec(
        "diff_parsers",
        "Exact Claude and Codex patch extraction.",
        (
            "_tooluse_file_stats",
            "_input_exact_diff",
            "extract_claude_exact_patches",
            "extract_codex_exact_patches",
        ),
    ),
    ModuleSpec(
        "subagent_history",
        "Subagent history and targeted diff reporting.",
        ("gather_subagent_history", "cmd_subagents", "cmd_subagent_diff"),
    ),
    ModuleSpec("diffs", "Run-level exact diff reporting.", ("cmd_diff",)),
    ModuleSpec(
        "auth_rotation",
        "Explicit credential rotation and Claude identities.",
        ("_dump_private", "cmd_rotate_auth", "claude_account_email"),
    ),
    ModuleSpec(
        "usage_windows",
        "Provider quota windows and hard-wall policy.",
        (
            "fetch_claude_usage",
            "fetch_engine_usage",
            "usage_window",
            "weekly_window",
            "is_weekly_limit",
            "FIVE_H_SKIP",
            "FIVE_H_HARD",
            "SEVEN_D_SKIP",
            "SEVEN_D_HARD",
            "ORCH_5H_ROTATE",
            "ORCH_7D_ROTATE",
            "ENGINE_HAS_5H",
            "CODEX_5H_WINDOW_MAX_MIN",
            "engine_has_5h",
            "rotate_advice",
            "LIVE_SPREAD_WEIGHT",
            "LIVE_CONCURRENCY_CAP",
            "FANOUT_LANES_PER_ACCT",
            "default_fanout_cap",
            "FLEET_CONCURRENCY_CAP",
            "fleet_live_workers",
        ),
    ),
    ModuleSpec(
        "quota_deadlines",
        "Weekly quota deadline and reset policy.",
        (
            "ROTATE_5H_CEILING",
            "WEEKLY_BUCKET_S",
            "WEEKLY_HORIZON_S",
            "WEEKLY_TIEBREAK_WEIGHT",
            "weekly_reset_at",
            "weekly_deadline_tier",
            "ROTATE_CLAIM_TTL_S",
        ),
    ),
    ModuleSpec(
        "selection_claims",
        "Concurrency-safe rotation claims and ranking.",
        (
            "_rotate_claim_file",
            "_rotate_lock_file",
            "_rotation_claims",
            "_rotation_claim_count",
            "_claim_rotation_target",
            "rotation_rank",
            "pick_least_loaded",
        ),
    ),
    ModuleSpec(
        "selection",
        "Usage-aware worker account selection.",
        ("_reset_eta", "pick_account"),
    ),
    ModuleSpec(
        "orchestrator_selection",
        "Usage-aware Neomax orchestrator selection.",
        (
            "ORCH_ANTI_STACK_WEIGHT",
            "pick_orch_account",
            "cmd_pick_orch",
            "_neomax_priority",
            "_neomax_selection_state",
            "_neomax_usage_pressure",
            "pick_neomax_orchestrator",
            "cmd_pick_neomax",
            "cmd_orch_on",
        ),
    ),
    ModuleSpec(
        "solo",
        "Single-account Claude mode and in-place failover.",
        (
            "SOLO_5H_ROTATE",
            "SOLO_7D_ROTATE",
            "_solo_profile",
            "_native_claude_accounts",
            "_copy_claude_auth",
            "_swap_claude_auth",
            "solo_pick_freshest",
            "solo_rotate",
            "cmd_solo_rotate",
            "cmd_solo_setup",
        ),
    ),
    ModuleSpec(
        "rotation_state",
        "Armed rotation state and account cooldowns.",
        (
            "ACCOUNT_COOLDOWN_FILE",
            "ARMED_ROTATE_FILE",
            "ARMED_ROTATE_AGE_S",
            "_armed_rotate_map",
            "_write_armed_rotate",
            "set_armed_rotate",
            "clear_armed_rotate",
            "armed_rotate_take",
            "_account_cooldowns",
            "_account_cooled",
            "_cool_account",
            "_current_session_profile",
        ),
    ),
    ModuleSpec(
        "rotation",
        "Universal provider session rotation.",
        ("session_rotate", "_NUMWORDS"),
    ),
    ModuleSpec(
        "rotation_commands",
        "Rotation command parsing and dispatch.",
        (
            "_parse_account_selectors",
            "cmd_session_rotate",
            "cmd_rotate",
            "_profile_recently_active",
        ),
    ),
    ModuleSpec(
        "runs",
        "Durable run registry, event log, and permanent history.",
        (
            "ensure_dirs",
            "log_event",
            "read_events",
            "run_path",
            "save_run",
            "load_run",
            "all_runs",
            "history_conn",
            "HISTORY_PENDING",
            "archive_run",
            "history_runs",
            "history_get",
            "pid_alive",
        ),
    ),
    ModuleSpec(
        "orchestrators",
        "Concurrent orchestrator coordination and liveness.",
        (
            "ORCH_DIR",
            "ORCH_GC_AGE_S",
            "_orch_path",
            "register_orchestrator",
            "orchestrator_heartbeat",
            "unregister_orchestrator",
            "all_orchestrators",
            "live_orchestrators",
            "orchestrators_on_account",
            "colocation_banner",
            "current_orch_session",
            "run_owner",
            "owned_by_other_live_orch",
            "_proc_is_engine",
            "_group_has_engine",
            "worker_alive",
            "TERMINAL_STATUSES",
            "is_acknowledged",
            "in_inbox",
            "effective_status",
        ),
    ),
    ModuleSpec(
        "gitops",
        "Git worktrees, pull requests, and change outcomes.",
        (
            "git",
            "has_remote",
            "default_branch",
            "existing_pr",
            "open_pr",
            "NotIsolable",
            "make_worktree",
            "worktree_changes",
            "worktree_outcome",
        ),
    ),
    ModuleSpec(
        "worker_commands",
        "Provider worker command construction and execution.",
        (
            "claude_args",
            "codex_args",
            "opencode_args",
            "kimi_args",
            "kimi_plan_home",
            "grok_args",
            "worker_argv",
            "execute",
            "CODEX_AUTH_DEAD",
            "CODEX_LIMIT",
        ),
    ),
    ModuleSpec(
        "event_parsers",
        "Shared, Claude, and Codex event parsing.",
        ("_new_parse_out", "parse_events", "parse_claude_events", "parse_codex_events"),
    ),
    ModuleSpec(
        "provider_event_parsers",
        "OpenCode, Kimi, and Grok event parsing.",
        (
            "_opencode_reset_epoch",
            "parse_opencode_events",
            "parse_kimi_events",
            "parse_grok_events",
        ),
    ),
    ModuleSpec(
        "usage_records", "Normalized provider usage recording.", ("record_usage",)
    ),
    ModuleSpec(
        "codex_usage",
        "Codex quota parsing and run finalization.",
        (
            "read_codex_window",
            "CODEX_USAGE_FRESH_S",
            "_normalize_codex_windows",
            "fetch_codex_usage",
            "tail_file",
            "finish",
            "maybe_cooldown",
            "remember_session",
            "CROSS_ENGINE_NOTE",
        ),
    ),
    ModuleSpec(
        "failover",
        "Cross-account and cross-provider worker failover.",
        ("_cross_engine_switch", "cross_engine_order", "run_with_failover"),
    ),
    ModuleSpec(
        "run_lifecycle",
        "Run safety gates, supervision, and pull-request lifecycle.",
        (
            "refuse_if_worker_alive",
            "refuse_if_other_orch",
            "ensure_workdir",
            "cmd_pr",
            "cmd_kill",
            "DELEGATION_BRIEF_MIN",
            "delegation_brief_check",
            "detach_supervisor",
            "cmd_supervise",
        ),
    ),
    ModuleSpec(
        "dispatch",
        "Worker dispatch, resume, and retry commands.",
        ("cmd_run", "cmd_resume", "cmd_retry"),
    ),
    ModuleSpec(
        "cleanup",
        "Run listing, logs, merge detection, and cleanup.",
        (
            "cmd_ls",
            "cmd_log",
            "remove_logs",
            "_git_main_ref",
            "run_merged_into_main",
            "_resolve_merged_run",
            "merged_terminal_runs",
            "cmd_tidy",
            "cmd_clean",
        ),
    ),
    ModuleSpec(
        "status_helpers",
        "Account identity and ambient-status helpers.",
        ("profile_acct_no", "account_identity", "live_children", "_solo_ambient"),
    ),
    ModuleSpec(
        "status",
        "Unified account, run, and session status aggregation.",
        ("gather_status",),
    ),
    ModuleSpec("history", "Permanent run-history command.", ("cmd_history",)),
    ModuleSpec(
        "handoff",
        "Interactive orchestrator handoff across profiles.",
        (
            "orchestrator_engine",
            "current_orchestrator_profile",
            "pick_freshest_account",
            "cmd_handoff",
            "_osa_escape",
        ),
    ),
    ModuleSpec(
        "mode_catalog",
        "Provider-neutral mode and command catalog.",
        ("_shell_quote", "ORCH_MODES", "ACCOUNT_CMDS"),
    ),
    ModuleSpec(
        "modes",
        "Mode discovery and command output.",
        ("orch_modes_lines", "cmd_modes", "_new_project_directive"),
    ),
    ModuleSpec(
        "orientation",
        "Provider-neutral orchestrator orientation.",
        ("orient_directive", "cmd_orient"),
    ),
    ModuleSpec(
        "usage_ingest",
        "Provider session-log usage ingestion.",
        (
            "_ledger_append",
            "_line_ts",
            "_claude_records_from_line",
            "_CODEX_MODEL_RE",
            "codex_model_in_line",
            "_codex_record_from_line",
            "_kimi_record_from_line",
            "USAGE_RECENT_DAYS",
            "_usage_session_files",
        ),
    ),
    ModuleSpec(
        "usage_watch",
        "Usage-ledger watch pass and state.",
        (
            "usage_watch_pass",
            "_save_watch_state",
            "KEEPALIVE_MARGIN_S",
            "KEEPALIVE_GAP_S",
            "KEEPALIVE_EVERY_S",
        ),
    ),
    ModuleSpec(
        "keepalive",
        "Provider credential keepalive policy.",
        (
            "_claude_token_expiry",
            "_codex_token_expiry",
            "keepalive_account",
            "keepalive_pass",
            "ROTATE_TICK_EVERY_S",
            "ROTATE_TICK_ACTIVE_GRACE_S",
        ),
    ),
    ModuleSpec(
        "rotation_watch",
        "Model-free rotation watcher and lifecycle hooks.",
        (
            "rotation_tick",
            "cmd_rotate_tick",
            "cmd_keepalive",
            "cmd_usage_watch",
            "_orchestrator_turn_reminder",
            "cmd_turn_hook",
            "cmd_model_guard",
            "cmd_usage_hook",
        ),
    ),
    ModuleSpec(
        "usage_aggregation",
        "Usage-ledger aggregation and duration parsing.",
        ("_read_usage_ledger", "gather_usage", "_parse_duration_s"),
    ),
    ModuleSpec(
        "usage_reports", "Usage and fleet-status commands.", ("cmd_usage", "cmd_status")
    ),
    ModuleSpec(
        "usage_search",
        "Usage search, acknowledgement, and audit commands.",
        ("cmd_find", "cmd_ack", "cmd_audit"),
    ),
    ModuleSpec(
        "area_locks",
        "Scheduler area locks and conflict boundaries.",
        (
            "PLANS_DIR",
            "LOCKS_DIR",
            "affected_area",
            "_lock_path",
            "_lock_stale",
            "_glob_locks",
            "acquire_area_lock",
            "release_area_locks",
            "UNION_SAFE_RE",
        ),
    ),
    ModuleSpec(
        "merge",
        "Mechanical integration and conflict resolution.",
        ("union_resolve", "try_mechanical_resolve", "integrate_part"),
    ),
    ModuleSpec("scheduler", "Dependency-aware multi-run scheduler.", ("cmd_run_all",)),
    ModuleSpec(
        "shepherd",
        "Continuous-integration classification and merge shepherd.",
        (
            "CI_NONRUN_CONCLUSIONS",
            "CI_REAL_FAIL_CONCLUSIONS",
            "classify_ci_checks",
            "cmd_shepherd",
        ),
    ),
    ModuleSpec(
        "reconcile",
        "Self-healing and detached worker reconciliation.",
        (
            "SELF_HEAL_FILE",
            "load_self_heal",
            "record_self_heal",
            "dispatch_detached",
            "kill_worker_inline",
            "cmd_reconcile",
        ),
    ),
    ModuleSpec(
        "account_controls",
        "Account pauses and orchestrator controls.",
        (
            "cmd_pause",
            "cmd_paused",
            "cmd_orch_register",
            "cmd_orch_unregister",
            "cmd_orchestrators",
        ),
    ),
    ModuleSpec(
        "premerge",
        "Premerge coordination and command usage.",
        ("cmd_premerge_check", "usage"),
    ),
    ModuleSpec(
        "github_client",
        "GitHub CLI access and project repository paths.",
        (
            "ISSUES_DIR",
            "ISSUE_LABEL",
            "GH_BIN",
            "ISSUE_STATUSES",
            "ISSUE_CLAIM_TTL_S",
            "gh_available",
            "gh_run",
            "gh_json",
            "project_repo_paths",
        ),
    ),
    ModuleSpec(
        "issue_store",
        "Durable issue storage, claiming, and deduplication.",
        (
            "_issue_path",
            "load_issue",
            "save_issue",
            "list_issues",
            "issue_event",
            "_session_live",
            "_claim_active",
            "claim_issue",
            "issue_fingerprint",
            "find_open_duplicate",
        ),
    ),
    ModuleSpec(
        "cross_repo_issues",
        "Cross-repository issue lifecycle.",
        (
            "open_cross_repo_issue",
            "_create_cross_repo_issue",
            "issue_comment_all",
            "close_cross_repo_issue",
            "reconcile_issues",
        ),
    ),
    ModuleSpec(
        "issue_ci",
        "Continuous-integration issue synchronization.",
        ("NEOMAX_CI_WORKFLOW", "NEOMAX_CI_SENTINEL", "ci_sync", "_issue_brief"),
    ),
    ModuleSpec(
        "queue",
        "Global agent-budget admission queue.",
        (
            "AGENT_QUEUE_FILE",
            "AGENT_BUDGET_DEFAULT",
            "TASK_BUDGET_DEFAULT",
            "QUEUE_RES_TTL_S",
            "load_queue",
            "_session_known_dead",
            "_res_alive",
            "allocate",
            "_queue_rmw",
            "queue_reserve",
            "queue_poll",
            "queue_release",
            "queue_set",
            "queue_snapshot",
            "cmd_queue",
        ),
    ),
    ModuleSpec(
        "issue_commands",
        "Issue and CI command handlers.",
        ("_issue_argparse", "cmd_issue", "cmd_ci_sync"),
    ),
    ModuleSpec(
        "cli",
        "Command authorization and top-level CLI dispatch.",
        ("require_orchestrator", "main"),
    ),
)
